services:
  - type: worker
    name: boxup-bot
    runtime: python
    repo: https://github.com/your-username/your-repo-name
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - fromGroup: boxup-env
